# Generated by Django 4.0.3 on 2022-04-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Yellow', 'Yellow'), ('Red', 'Red'), ('Green', 'Green'), ('Orange', 'Orange'), ('Black', 'Black')], default='Yellow', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S'), ('XS', 'XS')], default='M', max_length=6, null=True),
        ),
    ]
