# Generated by Django 4.0.3 on 2022-03-17 17:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0003_vendors_is_vendor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendors',
            new_name='Vendor',
        ),
    ]
