# Generated by Django 4.0.3 on 2022-03-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_vendor_options_remove_vendor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
