# Generated by Django 4.0.3 on 2022-03-24 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_rename_created_by_vendor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
    ]
