# Generated by Django 4.0.3 on 2022-04-11 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_created_at_orderitem_size_orderitem_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0009_remove_vendor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='order',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL),
        ),
    ]
