# Generated by Django 4.0.3 on 2022-04-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_vendor_last_login'),
        ('vendors', '0012_vendor_county_vendor_gender'),
    ]

    operations = [
    ]
