# Generated by Django 4.0.2 on 2022-02-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='CartItem',
        ),
    ]
