# Generated by Django 4.0.3 on 2022-04-11 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_remove_vendor_order_mycart'),
        ('order', '0002_orderitem_created_at_orderitem_size_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='vendors.vendor'),
        ),
    ]
